// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trcjlvdkvjynlfeaaflt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyY2psdmRrdmp5bmxmZWFhZmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTI2MTQsImV4cCI6MjA2NDcyODYxNH0.EoE84IO8tkG5qi4gMjw79wij_KMmzzxoQNPiekT9iTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);